from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field, HttpUrl


class Sentiment(StrEnum):
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"
    MIXED = "mixed"


class SentimentStrength(StrEnum):
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"


class Materiality(StrEnum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class ImpactDirection(StrEnum):
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"
    UNCERTAIN = "uncertain"


class TimeHorizon(StrEnum):
    SHORT_TERM = "short_term"
    MEDIUM_TERM = "medium_term"
    LONG_TERM = "long_term"
    UNCERTAIN = "uncertain"


class NewsArticle(BaseModel):
    """
    Normalized representation of a web article or market-information page.

    This model contains source facts only. It must not contain investment
    conclusions generated by the scraping layer.
    """

    source: str = Field(min_length=1)
    title: str = Field(min_length=1)
    url: HttpUrl
    published_at: datetime | None = None
    author: str | None = None
    content: str = Field(min_length=1)
    ticker: str = Field(min_length=1)


class MarketEvent(BaseModel):
    """
    Structured interpretation of a piece of market information.

    Produced by Gemini's research/extraction layer.
    """

    ticker: str = Field(min_length=1)
    event_type: str = Field(min_length=1)
    title: str = Field(min_length=1)
    summary: str = Field(min_length=1)

    sentiment: Sentiment
    sentiment_strength: SentimentStrength

    materiality: Materiality
    potential_impact: ImpactDirection

    affected_areas: list[str]
    time_horizon: TimeHorizon
    entity_scope: str = Field(min_length=1)
    source: str = Field(min_length=1)
    source_url: HttpUrl
    published_at: datetime | None = None


class MarketIntelligenceAnalysis(BaseModel):
    """
    Final market-intelligence decision synthesized from multiple events.
    """

    ticker: str = Field(min_length=1)

    score: float = Field(ge=0, le=100)

    overall_sentiment: Sentiment
    sentiment_strength: SentimentStrength

    summary: str = Field(min_length=1)

    key_events: list[MarketEvent]

    positive_factors: list[str]
    negative_factors: list[str]

    catalysts: list[str]
    risks: list[str]

    short_term_outlook: ImpactDirection
    medium_term_outlook: ImpactDirection
    long_term_outlook: ImpactDirection

class GroundedMarketEvidence(BaseModel):
    ticker: str = Field(min_length=1)
    title: str = Field(min_length=1)
    source: str = Field(min_length=1)
    url: HttpUrl
    published_at: datetime | None = None
    summary: str = Field(min_length=1)
    reason: str = Field(min_length=1)
    entity_scope: str = Field(min_length=1)